version: '3.8'

services:
  nodejs-argo:
    image: nodejs-argo:latest
    build: .
    container_name: nodejs-argo
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      ARGO_PORT: 8001
      FILE_PATH: ./tmp
      SUB_PATH: 778899
      UUID: 
      CFIP: cdns.doon.eu.org
      CFPORT: 443
      NAME: Vls
      ARGO_DOMAIN: hm.83121971.dpdns.org
      ARGO_AUTH: 
      KOMARI_ENDPOINT: 
      KOMARI_TOKEN: 
      UPLOAD_URL: ""
      PROJECT_URL: https://www.google.com
      AUTO_ACCESS: "false"
    volumes:
      - ./data:/app/tmp
